config/routes.rb
Rails.application.routes.draw do
  
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'  

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
  
  resources :tasks
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/task.rb
class Task < ApplicationRecord
	validates_presence_of :title, :content
	scope :order_by_created_at, ->{ order(created_at: :asc) }
	scope :order_by_end_time, ->{ order(end_time: :asc) }
	scope :search_status_type, ->(p) { where("status_type LIKE ?", p) }
	scope :search_title_or_content, ->(p) { where('title LIKE ? OR content LIKE ?', p, p) }
	# enum priority: { 高: 0, 中: 1, 低: 2 }
	# scope :priority_order, order(:priority)
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks, dependent: :destroy
	has_secure_password

	validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: I18n.t(:必須是有效的Email樣版) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_timezone

	def set_timezone
	   # if current_user && current_user.time_zone
	   #    Time.zone = current_user.time_zone
	   #  end
	   Time.zone = "Taipei"
	end

	before_action :set_current_user

	def set_current_user
		if session[:user_id]
	      Current.user = User.find_by(id: session[:user_id])
	    end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # render plain: "Thanks!"
    # render plain: params[:user]  
    #打印 {"email"=>"exite@gmail.com", "password"=>"123", "password_confirmation"=>"12"}

    # @user = User.new(params[:user])
    # User.new({email: "other.goto.com", password: "password", password_confirmation: "password"})

    # @user = User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: I18n.t(:創建帳號成功樣版)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)      
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user = User.find_by(email: params[:email])
		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to tasks_path, notice: I18n.t(:新增任務成功樣版)
		else
			flash[:alert] = I18n.t(:無效的Email帳號或密碼樣版)
			render :new
		end
		
	end

	def destroy
		session[:user_id] = nil
		redirect_to sign_in_path, notice: I18n.t(:登出樣版)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
		
		@tasks = Task.order(params[:sort])

		if params[:title] || params[:status]
			@tasks = Task.search_title_or_content( "%"+params[:title]+"%" )			
			.search_status_type("%"+params[:status]+"%")
			.order_by_created_at
			.page(params[:page]).per(6)

		elsif params[:sort]
        	@tasks = Task.order(params[:sort]).page(params[:page]).per(6)

        else
            @tasks = Task.order_by_created_at.page(params[:page]).per(6)

        end

	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(task_params)

		if @task.save
		# 成功
		redirect_to tasks_path, notice: I18n.t(:新增任務成功樣版)
		else
		# 失敗
		render :new
    	end
	end

	def edit
		@task = Task.find_by(id: params[:id])
	end

	def update
		@task = Task.find_by(id: params[:id])

		if @task.update(task_params)
		# 成功
		redirect_to tasks_path, notice: I18n.t(:資料更新成功樣版)
		else
		# 失敗
		render :edit
		end
	end

	def destroy
		@task = Task.find_by(id: params[:id])
		@task.destroy if @task
		redirect_to tasks_path, notice: I18n.t(:任務資料已刪除樣版)
	end

	private
		def task_params
		params.require(:task).permit(:title, :content, :end_time, :status_type, :priority_type)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container"> 
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to I18n.t(:首頁樣版), root_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <span class="navbar-text"><%= Current.user.email %></span>
          </li> 
          <li class="nav-item">
            <%= link_to I18n.t(:登出樣版), logout_path, method: :delete, class: 'nav-link' %>
          </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to I18n.t(:註冊樣版), sign_up_path, class: 'nav-link' %>
          </li> 
          <li class="nav-item">
            <%= link_to I18n.t(:登入樣版), sign_in_path, class: 'nav-link' %>
          </li> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

  <% if task.errors.any? %>    
      <h2><%= pluralize(task.errors.count, I18n.t(:錯誤樣版)) %> <%= t('禁止儲存此任務樣版') %></h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
  <% end %>

  <%= f.label :title, I18n.t(:任務標題樣版) %>
  <%= f.text_field :title ,class: 'form-control'%> <br />

  <%= f.label :content, I18n.t(:任務內容樣版) %>
  <%= f.text_field :content ,class: 'form-control'%> <br />

  <%= f.label :end_time, I18n.t(:結束時間樣版) %>
  <%= f.time_field :end_time ,type: "datetime-local",class: 'form-control' %> <br />

  <%= f.label :status_type, I18n.t(:狀態樣版) %>
  <%= f.select(:status_type, options_for_select([['待處理','待處理'],['進行中','進行中'], ['完成','完成']]), prompt: "請選擇狀態") %> <br />

  <%= f.label :priority_type, I18n.t(:優先順序樣版)  %>
  <%= f.select(:priority_type, options_for_select([['高','高'],['中','中'], ['低','低']]), prompt: "請選擇優先順序") %> <br />

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="mt-3">
	<h3><%= t('編輯任務樣版') %></h3>
</div>

<%= render "form", task: @task %>

<br />
<%= link_to I18n.t(:回任務列表樣版), tasks_path, class: 'btn btn-primary' %> 

app/views/tasks/index.html.erb
<div class="mt-3 d-flex align-items-center justify-content-center">
  <h2><%= t('任務列表樣版') %></h2>
</div>
<div class="mb-3">
  <%= link_to I18n.t(:新增任務樣版), new_task_path, class: 'btn btn-primary' %>
</div>
<!--       <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->

<form action="/tasks">
  <input name="title">
  <select name="status">
    <option value="">全部</option>
    <option value="待處理"><%= t('待處理樣版') %></option>
    <option value="進行中"><%= t('進行中樣版') %></option>
    <option value="完成"><%= t('完成樣版') %></option>
  </select>
  <button><%= t('搜尋樣版') %></button>  
</form>

<br>

<table class="table table-hover">
  <thead class="table-light">
    <tr>
      <td><%= t('任務標題樣版') %></td>
      <td><%= t('任務內容樣版') %></td>
      <td><%= link_to I18n.t(:創建時間樣版), :sort => "created_at" %></td>
      <td><%= link_to I18n.t(:結束時間樣版), :sort => "end_time" %></td>
      <td><%= t('狀態樣版') %></td>
      <td><%= link_to I18n.t(:優先順序樣版), :sort => "priority_type" %></td>
      <td><%= t('處理樣版') %></td>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
      <td><%= task.end_time %></td>
      <td><%= task.status_type %></td>
      <td><%= task.priority_type %></td>
      <td>
        <%= link_to I18n.t(:編輯樣版), edit_task_path(task) %>
        <%= link_to I18n.t(:刪除樣版), task_path(task), method: "delete", data: { confirm: I18n.t(:確認刪除樣版) } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<div class="mt-3">
	<h3><%= t('新增任務樣版') %></h3>
</div>

<%= render "form", task: @task %>

<br />
<%= link_to I18n.t(:回任務列表樣版), tasks_path, class: 'btn btn-primary' %>